packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog:

catalogs:
  dev:
    '@antfu/eslint-config': ^5.3.0
    '@antfu/ni': ^23.3.1
    '@antfu/utils': ^9.2.0
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    bumpp: ^10.2.3
    eslint: ^9.35.0
    esno: ^4.8.0
    lint-staged: ^15.5.2
    simple-git-hooks: ^2.13.1
    taze: ^19.6.0
    typescript: ^5.9.2
    unplugin-vue-components: ^28.8.0
    vite: ^7.1.6
    vite-tsconfig-paths: ^5.1.4
    vitest: ^3.2.4
  docs:
    '@shikijs/vitepress-twoslash': ^2.5.0
    floating-vue: ^5.2.2
    vitepress: ^2.0.0-alpha.12
    vitepress-plugin-group-icons: ^1.6.3
  frontend:
    '@unocss/reset': ^65.5.0
    '@vueuse/core': ^12.8.2
    pinia: ^3.0.3
    unocss: ^65.5.0
    vue: ^3.5.21
  icons:
    '@iconify-json/svg-spinners': ^1.2.4
  types:
    '@types/node': ^22.18.6
